# Generated by Django 4.2.6 on 2023-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='Vendor.jpg', upload_to='user_directory_path'),
        ),
    ]
