# Generated by Django 4.2.6 on 2023-11-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_life_product_mfd_product_stock_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='caht_resp_time',
            new_name='chat_resp_time',
        ),
    ]
